/**
 * Worker entry point — merges OpenNext's Next.js handler with our Durable Object.
 *
 * This file is referenced by wrangler.jsonc as `main`. Wrangler bundles it
 * together with the OpenNext output (in .open-next/) into the final Worker.
 *
 * Routing:
 *   /ws                          → Durable Object (WebSocket upgrade)
 *   /api/twitch/relay/*          → Durable Object (HTTP control endpoints)
 *   everything else              → Next.js handler (via OpenNext)
 *
 * The Durable Object class is re-exported so wrangler can find it via the
 * `class_name: "TwitchRelayDO"` binding in wrangler.jsonc.
 */

// Re-export the Durable Object class — wrangler picks this up from the entry
export { TwitchRelayDO } from "./TwitchRelayDO";

// OpenNext generates `.open-next/worker.js` which default-exports the Next.js handler.
// We import it statically so the bundler includes it.
//
// @ts-ignore — generated by OpenNext during `opennextjs-cloudflare build`
import openNextHandler from "../../.open-next/worker.js";

const DO_ID = "twitch-relay";

const worker = {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    const url = new URL(request.url);

    // Route WebSocket upgrades to the Durable Object
    if (url.pathname === "/ws" && request.headers.get("Upgrade") === "websocket") {
      const id = env.TWITCH_RELAY.idFromName(DO_ID);
      const stub = env.TWITCH_RELAY.get(id);
      return stub.fetch(request);
    }

    // Route relay control endpoints to the Durable Object
    if (url.pathname.startsWith("/api/twitch/relay/")) {
      const id = env.TWITCH_RELAY.idFromName(DO_ID);
      const stub = env.TWITCH_RELAY.get(id);
      const newPath = url.pathname.replace("/api/twitch/relay", "");
      const newUrl = new URL(newPath + url.search, url.origin);
      const newRequest = new Request(newUrl, request);
      return stub.fetch(newRequest);
    }

    // Everything else → Next.js (via OpenNext)
    return openNextHandler.fetch(request, env, ctx);
  },
};

export default worker;
