#!/usr/bin/env python3
"""
Package Tier Forge into a downloadable zip.

Includes:
  - All source code (src/, prisma/, mini-services/, scripts/, public/, examples/)
  - Config files (package.json, tsconfig.json, next.config.ts, tailwind.config.ts,
    postcss.config.mjs, eslint.config.mjs, components.json, Caddyfile, .gitignore)
  - README.md, worklog.md
  - bun.lock (for reproducible installs)
  - A sample .env file (with placeholder values, since the real .env contains
    the SQLite path which is needed)

Excludes (per .gitignore + common sense):
  - node_modules/ (huge, regenerated by `bun install`)
  - .next/ (build artifacts)
  - .zscripts/ (sandbox dev scripts)
  - .git/ (project history, optional but big)
  - skills/ (sandbox-only skill registry)
  - upload/ (sandbox upload staging)
  - db/*.db (regenerated by `bun run db:push`)
  - dev.log, server.log, *.log
  - download/ (screenshots we generated during verification — kept only for README banner)
"""

import os
import sys
import zipfile
from pathlib import Path

PROJECT_ROOT = Path("/home/z/my-project")
OUTPUT_ZIP = Path("/home/z/my-project/download/tier-forge-cloudflare.zip")
PROJECT_NAME = "tier-forge"

# Directories to include (relative to project root)
INCLUDE_DIRS = [
    "src",
    "prisma",
    "mini-services",
    "scripts",
    "public",
    "examples",
]

# Individual files to include (relative to project root)
INCLUDE_FILES = [
    "README.md",
    "CLOUDFLARE_DEPLOY.md",
    "worklog.md",
    "package.json",
    "bun.lock",
    "tsconfig.json",
    "next.config.ts",
    "tailwind.config.ts",
    "postcss.config.mjs",
    "eslint.config.mjs",
    "components.json",
    "Caddyfile",
    ".gitignore",
    "next-env.d.ts",
    "open-next.config.ts",
    "wrangler.jsonc",
    ".env.example",
]

# Patterns to exclude within included dirs
EXCLUDE_PATTERNS = [
    "node_modules",
    ".next",
    ".DS_Store",
    "__pycache__",
    "*.log",
    "*.db",
    "*.db-journal",
    "relay.log",
    ".bun",
]

# Specific subpaths to exclude even if within INCLUDE_DIRS
EXCLUDE_PATHS = {
    Path("mini-services/twitch-relay/node_modules"),
    Path("mini-services/twitch-relay/relay.log"),
    Path("examples/websocket/node_modules"),
}


def should_exclude(path: Path) -> bool:
    """Return True if this path should be excluded from the zip."""
    # Check explicit exclude paths
    try:
        rel = path.relative_to(PROJECT_ROOT)
    except ValueError:
        return True

    # Check if any exclude path is a prefix
    for ex in EXCLUDE_PATHS:
        try:
            rel.relative_to(ex)
            return True
        except ValueError:
            pass

    # Check patterns
    for part in rel.parts:
        for pat in EXCLUDE_PATTERNS:
            if pat.startswith("*"):
                if part.endswith(pat[1:]):
                    return True
            elif part == pat:
                return True

    return False


def main():
    if OUTPUT_ZIP.exists():
        OUTPUT_ZIP.unlink()

    file_count = 0
    total_bytes = 0

    with zipfile.ZipFile(OUTPUT_ZIP, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        # Add individual files
        for fname in INCLUDE_FILES:
            src = PROJECT_ROOT / fname
            if src.exists() and src.is_file():
                arcname = Path(PROJECT_NAME) / fname
                zf.write(src, arcname)
                file_count += 1
                total_bytes += src.stat().st_size
                print(f"  + {fname} ({src.stat().st_size:,} bytes)")
            else:
                print(f"  - skip {fname} (not found)")

        # Add a sample .env file (the real one has the SQLite path)
        env_sample = """# Database
DATABASE_URL="file:/home/z/my-project/db/custom.db"

# Next.js
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="change-me-in-production"
"""
        zf.writestr(str(Path(PROJECT_NAME) / ".env"), env_sample)
        file_count += 1
        print("  + .env (sample)")

        # Add directories
        for dirname in INCLUDE_DIRS:
            dirpath = PROJECT_ROOT / dirname
            if not dirpath.exists():
                print(f"  - skip dir {dirname}/ (not found)")
                continue

            for root, dirs, files in os.walk(dirpath):
                root_path = Path(root)
                # Filter dirs in-place to prevent descending into excluded ones
                dirs[:] = [
                    d for d in dirs
                    if not should_exclude(root_path / d)
                ]

                for f in files:
                    fp = root_path / f
                    if should_exclude(fp):
                        continue
                    rel = fp.relative_to(PROJECT_ROOT)
                    arcname = Path(PROJECT_NAME) / rel
                    zf.write(fp, arcname)
                    file_count += 1
                    total_bytes += fp.stat().st_size

            file_count_in_dir = sum(
                1 for _ in (
                    fp for fp in dirpath.rglob("*")
                    if fp.is_file() and not should_exclude(fp)
                )
            )
            print(f"  + {dirname}/ ({file_count_in_dir} files)")

    zip_size = OUTPUT_ZIP.stat().st_size
    print()
    print(f"✓ Created: {OUTPUT_ZIP}")
    print(f"  Files:    {file_count}")
    print(f"  Source:   {total_bytes:,} bytes")
    print(f"  Zipped:   {zip_size:,} bytes ({zip_size / total_bytes * 100:.1f}% compression)")


if __name__ == "__main__":
    main()
